#! /bin/bash

echo Rendering now...
echo Running Knitr...
Rscript -e "library(knitr); knit(input = './manuscript.Rmd', output = './manuscript.md')"
echo Running Pandoc...
pandoc --latex-engine=xelatex --template=customtemplate.tex -H options.sty -s ./manuscript.md -f markdown -t latex -o ./manuscript.tex --biblio=citations.bib --csl=./mbio.csl
xelatex manuscript.tex
xelatex manuscript.tex
rm missfont.log
rm manuscript.tex
rm manuscript.log
rm manuscript.aux
